#!/bin/sh
#
# Copyright (c) 2021 AmadeusGhost
# Adapted for iStoreOS (no WiFi)
#

. /lib/functions/leds.sh
. /lib/functions/uci-defaults.sh

board_config_update

board=$(board_name)

case "$board" in
zn,m2)
	ucidef_set_led_netdev "wan" "WAN" "m2:blue:wan" "eth0" "link tx rx"
	ucidef_set_led_netdev "lan" "LAN" "m2:blue:lan" "br-lan" "link tx rx"
	;;
esac

board_config_flush

exit 0
