#!/bin/bash
#
# Generate release tag and name
#

set -euo pipefail

DATE=$(date +%Y.%m.%d)
TIME=$(date +%H%M)
TIMESTAMP="$DATE.$TIME"

# Check if we're on a scheduled build or manual dispatch
if [ "${GITHUB_EVENT_NAME:-}" = "schedule" ]; then
    RELEASE_NAME="ZN-M2 Auto Build $TIMESTAMP"
else
    RELEASE_NAME="ZN-M2 Manual Build $TIMESTAMP"
fi

TAG_NAME="$TIMESTAMP/zn-m2/basic"
GECOSAC_TAG="$TIMESTAMP/zn-m2/gecoosac-v2"

echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT
echo "release_tag=$TAG_NAME" >> $GITHUB_OUTPUT

# Create release notes
cat > release.txt << EOF
# ZN-M2 Firmware Build

**Build Time:** $(date '+%Y-%m-%d %H:%M:%S')
**Branch:** master
**Commit:** ${GITHUB_SHA:0:8}

## 固件说明

本固件基于 OpenWrt IPQ6000 平台编译，专为兆能 ZN-M2 路由器定制。

### 版本特点

- 内核版本：4.4.60
- 支持 USB 3.0（需硬改）
- 无 WiFi 驱动（精简版）
- 支持 iStoreOS 应用商店
- 集成 OpenClash 代理
- IPv6 支持

### 固件列表

| 类型 | 说明 |
|------|------|
| basic | 基础版，精简依赖 |
| gecoosac-v2 | 完整版，包含更多应用 |

### 刷写说明

1. 使用 uboot 在线升级功能刷入 `.ubi` 文件
2. 或通过 SSH 执行 `mtd write` 命令

### 登录信息

- 默认 IP: 192.168.1.1
- 用户名: root
- 密码: 空

---
*Generated by GitHub Actions*
EOF
